# .travis.yml created by Jet Lee

os: linux
dist: xenial  # Use Ubuntu 16.04 as our Travis CI environment
language: python
python: "2.7"  # Soon to be deprecated, will need to update.
env: YELLOW="\033[1;33m" \
     NC="\033[0m" # No Color

# =========================================
# Download dependencies
# =========================================
before_install:
  - sudo apt-get -qq update
  - pip install --upgrade matplotlib  # Need for opencv2.
#  - sudo apt-get -qq --download-only install libhdf5-serial-dev hdf5-tools

# =========================================
# Install dependencies.
# Note: Use pip for virtual environments, but apt-get is faster since it is pre-compiled.
# =========================================
install:
  # Install required dependencies
  - pip install --upgrade pylint  # Use pylint to verify code. Make sure to install with pip.
  - pip install --upgrade numpy Pillow pytesseract
  - pip install --upgrade opencv-python  # Requires matplotlib and numpy to also be installed.
#  - sudo apt-get -qq install python-numpy python-opencv

# =========================================
# Actually verify files
# =========================================
script:
  # Lint the Python files
  - echo -e "${YELLOW}Analyzing main.py...${NC}" && pylint --errors-only "$TRAVIS_BUILD_DIR"/main.py
  - echo -e "${YELLOW}Analyzing blur_image_region.py...${NC}" && pylint --errors-only "$TRAVIS_BUILD_DIR"/blur_image_region.py
